name: UpdraftShop
version: ${version}
main: updraftmc.shop.UpdraftShop
api-version: '1.21'
author: french and astro
softdepend:
  - Vault

commands:
  updraftshop:
    description: Opens the shop menu.
    usage: /updraftshop
    aliases: [ ushop ]
  shop:
    description: Opens the shop menu.
    usage: /shop
  sell:
    description: Sells the item in your hand. Optionally takes an amount, or "all".
    usage: /sell [amount|all]
  shophelp:
    description: Lists the shop commands.
    usage: /shophelp
